// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Crud.Entity
{
    public partial class EmployeeDetails
    {
        public int Employee_Id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public DateTime Date_Of_Joining { get; set; }
        public int Age { get; set; }
        public string Experience { get; set; }
        public long Contact_Number { get; set; }
        public string Address { get; set; }
        public int? Location_Id { get; set; }
        public string Password { get; set; }
        public string Confirm_Password { get; set; }
        public bool Is_Deleted { get; set; }
        public DateTime Created_Time_Stamp { get; set; }
        public DateTime Updated_Time_Stamp { get; set; }

        public virtual LocationDetails Location { get; set; }
    }
}