// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Crud.Entity
{
    public partial class LocationDetails
    {
        public LocationDetails()
        {
            EmployeeDetails = new HashSet<EmployeeDetails>();
        }

        public int Location_Id { get; set; }
        public string Work_Location { get; set; }
        public bool Is_Deleted { get; set; }
        public DateTime Created_Time_Stamp { get; set; }
        public DateTime Updated_Time_Stamp { get; set; }

        public virtual ICollection<EmployeeDetails> EmployeeDetails { get; set; }
    }
}